#! /usr/bin/env awk -f

/^dngchapter:/ {
    number = $2
    page = $3
    title = ""
    sep = ""
    for (i = 4; i <= NF; i++) {
        title = title sep $i
        sep = " "
    }
    gsub(/~/, " ", title)
    gsub(/'/, "’", title)
    gsub(/---/, "—", title)
    if (number > 0) {
        print lastpage "-" (page-1) " " lasttitle
    }
    lastnumber = number
    lastpage = page
    lasttitle = title
}
