#! /usr/bin/env zsh -df
setopt errexit pipefail

zparseopts -D -F -output:=output -css:=css
: ${css:?} ${output:?}
cmd=(
  pandoc
  --standalone
  --from=markdown
  --to=html
  ${css}
  ${output}
  ${argv}
)
run ${cmd}
