#! /usr/bin/env zsh -df

# q: Quote arguments.
# @: Expand into separate words.
print -Pru2 -- "%F{cyan}${(q-@)argv}%f"
${argv} || {
    print -Pru2 -- "%F{red}${argv[1]} failed with exit status ${rc::=$?}%f"
    exit ${rc}
}
print -Pru2 -- '%F{green}'$'\u2714'" ${argv[1]}%f"$'\n'
