#! /usr/bin/env zsh -df
setopt errexit pipefail

zparseopts -D -F -css:=css -filter+:=filter -prefix:=prefix -site:=site -output:=output
: ${css:?} ${filter:?} ${output:?}
base=${${(@)output:#--output}:r}
filter=( ${(@)filter:#--filter} )
prefix=( ${(@)prefix:#--prefix} )
site=( ${(@)site:#--site} )
cmd=(
  pandoc
  --standalone
  --from=markdown
  --top-level-division=chapter
  --dpi 300
  --to=html
  --metadata=basename:${base}
  --metadata=prefix:${^prefix}
  --metadata=site:${^site}
  --lua-filter=${^filter}
  ${css}
  ${output}
  ${argv}
)
run ${cmd}
