name: D&G CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  #v4.2.2
    - name: Install Nix
      uses: cachix/install-nix-action@02a151ada4993995686f9ed4f1be7cfbb229e56f  # v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build with Flake
      run: nix build .
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8  # v4.7.3
      with:
        folder: result
        git-config-name: Kragor Grimstride
        git-config-email: kragorg@github.com
        token: ${{ secrets.GITHUB_TOKEN }}
